# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z1_C.xdc

# Block Designs: bd/lab_2/lab_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2 || ORIG_REF_NAME==lab_2} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_processing_system7_0_0/lab_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_processing_system7_0_0 || ORIG_REF_NAME==lab_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_axi_regmap_0_0/lab_2_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_axi_regmap_0_0 || ORIG_REF_NAME==lab_2_axi_regmap_0_0} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_alu_0_0/lab_2_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_alu_0_0 || ORIG_REF_NAME==lab_2_alu_0_0} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_auto_pc_0/lab_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_auto_pc_0 || ORIG_REF_NAME==lab_2_auto_pc_0} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_ps7_0_axi_periph_0/lab_2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_2/ip/lab_2_rst_ps7_0_100M_0/lab_2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_2_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/lab_2/lab_2_ooc.xdc
