# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/alexivensky/ADDLabs/Lab-2/lab_2/lab_2.srcs/sources_1/bd/lab_2/ip/lab_2_auto_pc_0/lab_2_auto_pc_0.xci
# IP: The module: 'lab_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexivensky/ADDLabs/Lab-2/lab_2/lab_2.srcs/sources_1/bd/lab_2/ip/lab_2_auto_pc_0/lab_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/alexivensky/ADDLabs/Lab-2/lab_2/lab_2.srcs/sources_1/bd/lab_2/ip/lab_2_auto_pc_0/lab_2_auto_pc_0.xci
# IP: The module: 'lab_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexivensky/ADDLabs/Lab-2/lab_2/lab_2.srcs/sources_1/bd/lab_2/ip/lab_2_auto_pc_0/lab_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
